### PR TITLE
Update to support Less ^3.0.0

### LINKED ISSUE #8: .for & .for-each with Less 3.x
Just did a quick test (Windows 10, node v9.8.0, latest pnpm) .for & .for-each give:
 `undefinedError: Rule is not a constructor` under Less 3.0.1.

- Everything else seem to be working fine.
- Everything is working fine with Less 2.7.3

### PR DESCRIPTION
**Pull request by Matchlighter**
The title says it all. Fixes #8. Tests pass.

### CODE REVIEW

**Comment by seven-phases-max** [comment]
Thanks (especially for making it exactly the way I planned :) - though I thought to number it as 1.5 (since it's not really a breaking change). But never mind, 2 is OK too.

**Comment by seven-phases-max** [comment]
Unfortunately I won't be able to make the npm release any time soon (let me know if you are also able to do this - e.g. send me your npmjs profile name so I'll simply add you to the release team there - if you're fine with that of course).

**Comment by Matchlighter** [comment]
I bumped the Grunt plugin to 2.0.0, left this at 1.1.2 since that tag hasn't been released yet. I am 
[matchlighter](https://www.npmjs.com/~matchlighter) on NPM as well.

**Comment by seven-phases-max** [comment]
@Matchlighter Done (I think). And sorry for the delay.

**Comment by TigersWay** [comment]
Not done (I think) ...

> seven-phases-max published 1.1.1 • a year ago

Sorry!

**Comment by seven-phases-max** [comment]
@TigersWay By "Done" I mean I added @Matchlighter to the release team at npmjs.com.

**Comment by TigersWay** [comment]
@seven-phases-max My mistake then! I'll try to wait quietly :-)

**Comment by seven-phases-max** [comment]
(Either way, my apologizes I can't do any releases these days - it's a long story why - but I hope the situation changes sooner or later).

**Comment by Matchlighter** [comment]
Sorry for the delay. It's up now as version 1.1.2

**Comment by seven-phases-max** [comment]
Thanks!

**Pull request merged**
